### PR TITLE
Major Refactoring

### PR DESCRIPTION
**Pull request by akitaonrails**
This is a super nice project, it's basically a laboratory full of experiments.

I wanted to create a more organised structure so I could try to help evolve it. First of all I reorganised everything as a Ruby gem with proper native extension bits such as extconf.rb and a cross platform (OS X/Ubuntu) Makefile that compiles the proper shared-objects.

Moved scripts into 'bin', tests into a 'test' directory and so on.

I hope this is useful and I want to keep trying to help out (I added a Wish List at the end of the README file with what I want to possible pursue).

Let me know if you want me to change anything.

### CODE REVIEW

**Comment by phoffer** [comment]
Wow thank you! This is a ton of re-organization that has been overdue, but I just hadn't gotten to yet. The wishlist you added is nearly identical to what I've been planning.

I do intend to split this into two repos, one will be a Crystal shard containing lib_ruby and any other Crystal tooling. The other would be a gem which is more or less a generator. It would allow a user to create a new gem that utilizes the Crystal tooling, and possibly has some more tools to aid in development. That gem itself would utilize Crystal (albeit in very minor fashion). 

I would definitely appreciate any help you want to provide. Lately, I've been stuck dealing with the type conversions (instead of fun things like getting the project polished). I would really like to get that working soon, since that's vital to this project being useful (I had hoped to have that ready before it caught people's attention). There are a few other smaller issues, I will put together a concise list.

I would be happy to merge this, would you mind fixing the merge conflict? I have pushed some changes since your earlier PR. I believe the conflict is the updates section of the README, which I moved to `updates.md`.

One more thing, the test_inflector directory was what I was using for an example of a non-trivial Ruby extension, and is not vital to this repo. Eventually I am going to pull it into its own repo and hopefully gem. I had planned on doing so after the previously mentioned shard and gem were ready. Just wanted to explain its purpose, in case it was unclear.

**Comment by akitaonrails** [comment]
Hi @phoffer I just did the rebase, fixed conflicts and sent new commits to make it work. Let me know if you want anything else changed.

**Comment by akitaonrails** [comment]
Oh, and I didn't include your e-mail in the gemspec because I didn't find it anywhere :-) please feel free to edit the license file, gemspec file and any other bits.

**Comment by phoffer** [comment]
Awesome thank you. No worries about the gemspec, I can update it

**Pull request merged**
